# 200 skus task with lowest capacity.
# All skus are selected from sku 2778 with selling_price >= procurement_cost * 1.05
env:
  mode:
    - name: train
      start_date: 2018/8/1
      end_date: 2019/5/27
      random_interception: True
    - name: validation
      start_date: 2019/5/28
      end_date: 2019/9/4 
    - name: test
      start_date: 2019/9/5
      end_date: 2019/12/14
  horizon: 100
  lookback_len: 21
  integerization_sku: True
  storage_capacity: 5000
  initial_balance: 0
  warmup: replenish_by_last_demand

sku:
  sku_list: ReplenishmentEnv/data/sku2778/sku200.smooth_demand.sku_list.csv
  dynamic_info: 
    - name: demand
      file: ReplenishmentEnv/data/sku2778/sku2778.demand.csv
    - name: selling_price
      file: ReplenishmentEnv/data/sku2778/sku2778.selling_price.csv
    - name: procurement_cost
      file: ReplenishmentEnv/data/sku2778/sku2778.procurement_cost.csv
  static_info: ReplenishmentEnv/data/sku2778/sku2778.info.csv
  shared_info:
    order_cost: 10
    volume: 1
    storage_cost: 0.0025
    holding_cost_ratio: 0.00002

profit:
  profit_function: reward2
  backlog_ratio: 0
  excess_ratio: 0.5

reward:
  mode: same_as_profit

action:
  mode: demand_mean_continuous

output_state:
  current_state:
    [selling_price, procurement_cost, vlt, volume, 
    order_cost, replenish, excess, in_stock, in_transit]
  lookback_state:
    [demand]